DataBiosphere/terra-scientific-pipelines-service

README.md, service/build.gradle
sonar setup config with help from Tom Conner
=> update sonar info

README.md
[TSPS-15] - https://broadworkbench.atlassian.net/browse/TSPS-15
- Added a link to internal docs on Sonaqube
[TSPS-15]: https://broadworkbench.atlassian.net/browse/TSPS-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TSPS-15] Added link to internal SonarQube

service/src/main/java/bio/terra/pipelines/service/JobsService.java, service/src/test/java/bio/terra/pipelines/service/JobsServiceTest.java
Adding tests for the parts of JobsService that contain actual busines logic.  Also making the UUID generation protected, so I can override it using a spy.
=> [TSPS-29] Testing coverage for JobsService

README.md, common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java, service/src/test/java/bio/terra/pipelines/controller/JobsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java
I think this should do what we want, I definitely took a few wrong paths 😬.  I did think about using the [AnyValue type](https://swagger.io/docs/specification/data-models/data-types/#any) option but seemed a little too "blobby" for this.  I couldn't find any relevant tests to update since its just an empty object atm so not really anything to verify but let me know if I missed something.
=> TSPS-41 add PipelineInputs field to PostJobRequestBody

service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java, service/src/main/java/bio/terra/pipelines/db/entities/PipelineInput.java, service/src/main/java/bio/terra/pipelines/db/repositories/PipelineInputsRepository.java, service/src/main/java/bio/terra/pipelines/service/JobsService.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20230711.yaml, service/src/test/java/bio/terra/pipelines/controller/JobsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/JobsServiceMockTest.java, service/src/test/java/bio/terra/pipelines/service/JobsServiceTest.java
create a table to save the pipeline inputs passed in by the user when submitting a job to our service
=> TSPS-42 add pipeline_inputs table 

scripts/notebooks/azure_wds_cbas_testing.ipynb
Notebook used to help with de-risking WDS and CBAS.  Has all of the functions we would need to interact with both of those apps. We have some open questions around what actually needs to be provided when submitting a submission in terms of workflow_inputs and workflow_outputs but that will be settled outside of this notebook's code.  
I'm happy to do a walkthrough before this is merged as well
=> TSPS-67 added notebook interacting with WDS and CBAS

scripts/notebooks/azure_file_copy_testing.ipynb
Added the commands to copy from the "control" workspace to the "user" workspace as well.  Added some more comments to the existing notebook.  Removed the TSPS function calls
=> TSPS-69 update file copy testing notebook 

service/build.gradle, service/src/main/java/bio/terra/pipelines/app/configuration/external/WdsServerConfiguration.java, service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java, service/src/main/java/bio/terra/pipelines/dependencies/common/DependencyNotAvailableException.java, service/src/main/java/bio/terra/pipelines/dependencies/common/HealthCheckWorkspaceApps.java, service/src/main/java/bio/terra/pipelines/dependencies/leonardo/AppUtils.java, service/src/main/java/bio/terra/pipelines/dependencies/leonardo/LeonardoService.java, service/src/main/java/bio/terra/pipelines/dependencies/sam/SamClient.java, service/src/main/java/bio/terra/pipelines/dependencies/wds/WdsClient.java, service/src/main/java/bio/terra/pipelines/dependencies/wds/WdsService.java, service/src/main/java/bio/terra/pipelines/dependencies/wds/WdsServiceApiException.java, service/src/main/java/bio/terra/pipelines/dependencies/wds/WdsServiceException.java, service/src/main/java/bio/terra/pipelines/dependencies/wds/WdsServiceNotAvailableException.java, service/src/main/java/bio/terra/pipelines/service/ImputationService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/configuration/external/SamConfigurationTest.java, service/src/test/java/bio/terra/pipelines/dependencies/leonardo/AppUtilsTest.java, service/src/test/java/bio/terra/pipelines/dependencies/leonardo/LeonardoServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/wds/WdsClientTest.java, service/src/test/java/bio/terra/pipelines/dependencies/wds/WdsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/ImputationServiceMockTest.java, service/src/test/resources/application-test.yml
Add logic to interact with WDS client using a confingurable workspace id and the wds uri returned by Leonardo.  Currently it only queries the WDS for the list of data tables but has functions to get a row record and update a row record.  Will most likely need more functions in the future.
https://broadworkbench.atlassian.net/browse/TSPS-101
=> TSPS-101 add functionality to get wds client set up and working

service/src/main/java/bio/terra/pipelines/app/controller/PipelinesApiController.java, service/src/main/java/bio/terra/pipelines/service/ImputationService.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/ImputationServiceMockTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java
Title says it all
No jira ticket for this, just somethign we wanted to do for the demo
=> write flight id to the description of the submitted run set

common/openapi.yml, service/src/test/java/bio/terra/pipelines/controller/JobsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java
Update our endpoint version to v1 to be in line with https://docs.google.com/document/d/1qXNHTijdPn9ApYrznSkTFnxkt0g-o-Uh0SjqQlYd-ZA/edit for production readiness
https://broadworkbench.atlassian.net/browse/TSPS-103
=> TSPS-103 update our api version to v1 to match workbench standards

buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.pipelines.java-common-conventions.gradle, service/build.gradle
=> Revert dependency upgrades

common/openapi.yml
Added descriptions for a few endpoints that were missing them. Now all our endpoints have visible descriptions on swagger:
https://broadworkbench.atlassian.net/browse/TSPS-187
=> TSPS-187 Add missing descriptions for api endpoints

.github/actions/create-bee/action.yml, .github/actions/landing-zone-attach/action.yml, .github/workflows/run-e2e-tests.yaml
This PR adds the github workflow and actions to run our integration test.  The flow is described [here](https://lucid.app/lucidchart/36e399a2-ff15-49fd-b9ee-72701a6ec5af/edit?viewport_loc=-2248%2C-1167%2C1932%2C993%2C0_0&invitationId=inv_37e312bc-dca7-467a-99b2-a89ef69b06a2).  Still need to figure out on what cadence we want to launch this workflow but the infrastructure and flow is set up now.
https://broadworkbench.atlassian.net/browse/TSPS-124
=> TSPS-124 integration test infrastructure working with GHA

.github/workflows/run-e2e-tests.yaml
Title :)
No ticket, just a quick change
=> change e2e slack alert to completion insetad of just failure

.github/workflows/run-e2e-tests.yaml
=> git rid of extra colon

.github/actions/create-bee/action.yml
We want to use a bee template that has janitor enabled on it to clean up any orphaned resources.  We were asked to create our own template as opposed to updating the rawls one to include tsps.
N/A
=> update e2e test create-bee template

pipelines/simulatedData/Dockerfile, pipelines/simulatedData/README.md, pipelines/simulatedData/StdPopSim.wdl, pipelines/testing/ImputationBeagleEmpty.wdl, service/src/main/java/bio/terra/pipelines/stairway/imputation/PrepareImputationInputsStep.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240610_change_beagle_reference_path_input.yaml, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceDatabaseTest.java
stdpopsim is the tool we are currently using to generate fake reference panel data.  we wanted to wrap the tool in a docker so that will make it easier to run in the future.
Successful run of this wdl workflow for 10k samples - https://bvdp-saturn-dev.appspot.com/#workspaces/tsps_dev_bp_02_01_2024_v1/imputation-pipeline-testing-03-07-2024/workflows-app/submission-monitoring/178d57b6-fd77-436b-b29f-4e05215189e9/a682d5d3-a44c-4baf-a43a-9db15af14496
successrul of service launched workflow using the new 1000G reference path - https://bvdp-saturn-dev.appspot.com/#workspaces/tsps_dev_bp_04_22_2024_protect/TSPS_imputation_control_workspace_realWDL_20240521/workflows-app/submission-history/31b1c4fb-986b-4d66-a4ec-ec341c257e69
https://broadworkbench.atlassian.net/browse/TSPS-142
=> TSPS-142 Add wdl/dockerfile/ for stdpopsim tool

pipelines/testing/ImputationBeagleEmpty.wdl
i deleted an input in the empty beagle wdl so this is adding it back in!!
=> add back in contigs input to beagle empty wdl

service/src/main/java/bio/terra/pipelines/app/controller/GlobalExceptionHandler.java
Alert Sentry for 4** errors
https://broadworkbench.atlassian.net/browse/TSPS-228
=> TSPS-228 send 4** errors to sentry

service/src/main/java/bio/terra/pipelines/app/controller/PublicApiController.java, service/src/main/java/bio/terra/pipelines/dependencies/workspacemanager/WorkspaceManagerService.java, service/src/main/java/bio/terra/pipelines/service/BaseStatusService.java, service/src/main/java/bio/terra/pipelines/service/StatusService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/controller/PublicApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/StatusServiceTest.java
We weren't actually using our StatusService, now we are. This includes checking that Sam is healthy as well as our database connection.
https://broadworkbench.atlassian.net/browse/TSPS-267
=> TSPS-267 actually use our status service

service/src/main/java/bio/terra/pipelines/app/configuration/internal/ImputationConfiguration.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/PrepareImputationInputsStep.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/configuration/internal/ImputationConfigurationTest.java, service/src/test/resources/application-test.yml
Instead of hardcoding the storage workspace storage container URL, populate it via secret / environment variable.
terra-helmfile PR to add the secret: https://github.com/broadinstitute/terra-helmfile/pull/5715
https://broadworkbench.atlassian.net/browse/TSPS-242
=> TSPS-242 Retrieve storage workspace storage container url via secret rather than hardcoded value

service/src/main/java/bio/terra/pipelines/dependencies/rawls/RawlsService.java, service/src/main/java/bio/terra/pipelines/dependencies/rawls/RawlsServiceApiException.java, service/src/main/java/bio/terra/pipelines/dependencies/rawls/RawlsServiceException.java, service/src/main/java/bio/terra/pipelines/dependencies/workspacemanager/WorkspaceManagerServiceException.java, service/src/test/java/bio/terra/pipelines/dependencies/rawls/RawlsServiceTest.java
This is a class that multiple tickets will use so to help with dealign with conflicts we're just commiting a very basic version of this class
sort of part of https://broadworkbench.atlassian.net/browse/TSPS-276
=> TSPS-276 add base RawlsService class to build off of

service/src/main/resources/templates/index.html
Fix for the previous PR to accommodate dev.
Tested and works locally and in a BEE.
Associated terra-helmfire PR to work with local deployments: https://github.com/broadinstitute/terraform-ap-deployments/pull/1691
https://broadworkbench.atlassian.net/browse/TSPS-191
=> TSPS-191 - update redirect url specified in index.html

service/src/main/resources/templates/index.html
This is effectively a rollback of the previous PR. We are making corresponding changes in terraform-ap-deployments: https://github.com/broadinstitute/terraform-ap-deployments/pull/1693
https://broadworkbench.atlassian.net/browse/TSPS-191
=> TSPS-191 Really this time fix dev b2c authentication redirect url

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/AdminApiController.java, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/main/java/bio/terra/pipelines/db/entities/Pipeline.java, service/src/main/java/bio/terra/pipelines/service/PipelinesService.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240824_add_wdl_version_update_pipeline_version.yaml, service/src/test/java/bio/terra/pipelines/controller/AdminApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
Also update the admin endpoint to allow for this field to be updateable and retried from the different admin endpoints.
Note that the wdl method version should be aligned with the pipeline version through the major version of the wdl method version
https://broadworkbench.atlassian.net/browse/TSPS-302
=> TSPS-302 add wdlMethodVersion to pipelines table

common/openapi.yml, service/build.gradle, service/src/main/java/bio/terra/pipelines/app/configuration/external/GcsConfiguration.java, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/main/java/bio/terra/pipelines/dependencies/gcs/GcsClient.java, service/src/main/java/bio/terra/pipelines/dependencies/gcs/GcsService.java, service/src/main/java/bio/terra/pipelines/dependencies/gcs/GcsServiceException.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/configuration/external/GcsConfigurationTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/dependencies/gcs/GcsClientTest.java, service/src/test/java/bio/terra/pipelines/dependencies/gcs/GcsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java
Note: #118 contains updates that affect this PR; if that one is merged first, will need to update this PR.
The result of preparePipelineRun is now:
```{
"jobId": "ffaffa12-5717-4562-b3fc-2c963f66afa6",
"fileInputUploadUrls": {
"multiSampleVcf": {
"signedUrl": "https://storage.googleapis.com/fc-secure-6970c3a9-dc92-436d-af3d-917bcb4cf05a/user-input-files/ffaffa12-5717-4562-b3fc-2c963f66afa6/TEST.vcf.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=tsps-dev%40broad-dsde-dev.iam.gserviceaccount.com%2F20240823%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240823T170006Z&X-Goog-Expires=900&X-Goog-SignedHeaders=content-type%3Bhost&X-Goog-Signature=[redacted]",
"curlCommand": "curl -X PUT -H 'Content-Type: application/octet-stream' --upload-file TEST.vcf.gz …
```
=> TSPS-305 Add GCS service, sign PUT urls for data uploads

pipelines/simulatedData/CreateImputationRefPanelBeagle.wdl, pipelines/simulatedData/README.md, pipelines/simulatedData/StdPopSim.wdl
We generated simulated reference panel data to use for testing and this PR is adding those wdls to this repo in case we want to generate more in the future
https://broadworkbench.atlassian.net/browse/TSPS-142
=> TSPS-142 add wdls used to create simulated ref panel for imputation beagle

README.md, scripts/git-hooks/README.md, scripts/git-hooks/pre-commit, settings.gradle
Copied from WDS: https://github.com/DataBiosphere/terra-workspace-data-service/tree/main/scripts/git-hooks
none
=> Add git hook to run spotlessApply on pre-commit

.dockstore.yml, pipelines/imputation/simulatedData/DuplicateVcfAndMerge.wdl, pipelines/imputation/simulatedData/README.md
This adds the wdl we used to generate our multisample input vcf
https://broadworkbench.atlassian.net/browse/TSPS-239
=> TSPS-239 add duplicateandmerge wdl

service/src/main/java/bio/terra/pipelines/service/PipelinesService.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java
we want to update our wdlmethodversion check so that we can use wdls released in warp
=> update wdlMethodVersion regex check to work with warp tag patterns

service/publishing.gradle
this is to address https://github.com/GoogleContainerTools/distroless/issues/1685 which was discussed [here](https://broadinstitute.slack.com/archives/C0DSD41QT/p1728328182615109)
https://broadworkbench.atlassian.net/browse/TSPS-336
=> TSPS-336 update docker base image for creating service image to jre:17-12-distroless

.github/workflows/release-python-client.yml, .github/workflows/tag-publish.yml
Previous PR failed to remove a job dependency, making this workflow invalid. Then I found a bunch more that was wrong with it. 
https://broadworkbench.atlassian.net/browse/TSPS-367
=> TSPS-367 fix again: remove old job dependency

service/src/main/java/bio/terra/pipelines/db/entities/UserQuota.java, service/src/main/java/bio/terra/pipelines/db/repositories/UserQuotasRepository.java, service/src/main/java/bio/terra/pipelines/service/QuotasService.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20241103_add_user_quotas.yaml, service/src/test/java/bio/terra/pipelines/db/entities/UserQuotaTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java
This PR adds in the user quotas table and a little bit of logic to create a new row in the user quotas table when a get request is made and no row exists.
https://broadworkbench.atlassian.net/browse/TSPS-355
=> TSPS-355 add in user quotas logic

service/src/main/java/bio/terra/pipelines/app/configuration/internal/WdlPipelineConfiguration.java, service/src/main/java/bio/terra/pipelines/stairway/SubmitQuotaConsumedSubmissionStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpJobFlight.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/stairway/SubmitQuotaConsumedSubmissionStepTest.java, service/src/test/resources/application-test.yml
* made call caching value for quota consumed wdls configurable
* set call caching to false for all wdls run in our service
https://broadworkbench.atlassian.net/browse/TSPS-386
=> TSPS-386 turn call caching off for wdls

notification-templates/README.md, notification-templates/job_failed.html, notification-templates/job_succeeded.html, settings.gradle
Keeping a copy of the html files that are used by Twilio/SendGrid for email notifications.
The screenshots of rendered html for these files are also here: https://docs.google.com/document/d/1qre8EmSF8Kp-GflziAr-q4-NYKCn8nMOx8tGmFBBOyM/edit?tab=t.0#heading=h.2t2eluyc5na9
https://broadworkbench.atlassian.net/browse/TSPS-372
=> TSPS-372 add email notification template files

.github/actions/create-bee/action.yml, .github/workflows/run-e2e-tests.yaml
This is the first part of trying to get our e2e test runnable from a beehive post deploy hook so that we can test the staging deployment 
https://broadworkbench.atlassian.net/browse/TSPS-424
=> TSPS-424 parameterize version template for staging post deploy hook

README.md, pull_request_template.md, scripts/write-config.sh
Our e2e test failed during a staging release and DevOps would find it useful to have a list of services we depend on so they could better triage our test failures
N/A
=> add some updates to readme

.github/actions/create-bee/action.yml
actually pass run name to workflow dispatch action 
N/A
=> pass in run name to workflow dispatch action

buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.pipelines.java-common-conventions.gradle, gradle/wrapper/gradle-wrapper.properties, service/build.gradle, service/src/main/java/bio/terra/pipelines/App.java, service/src/main/resources/application.yml
To support an eventual change we're making in TCL, we're separately updating the TCL version, since there are breaking changes to opentelemetry brought in with the updated TCL version.
Also taking this opportunity to enable tracing.
No ticket for updating TCL
Add tracing ticket: https://broadworkbench.atlassian.net/browse/TSPS-107
=> Add tracing, update TCL to 1.1.35 and Spring Boot to 3.4.2

README.md
This PR contains some documentation updates for users new to setting up TSPS
[TSPS-453
](https://broadworkbench.atlassian.net/browse/TSPS-453)
=> TSPS-453 README documentation updates

ui/allofus-anvil-imputation/css/style.css, ui/allofus-anvil-imputation/index.html
This refines some wording per Beth, to help users understand what AnVIL means in terms of the data we are talking about.
https://broadworkbench.atlassian.net/browse/TSPS-468
=> TSPS-468 Clarify meaning of AnVIL in marketing UI

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelinesApiController.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
Adds the pipeline quota settings to the getPipelineDetails response.
Needed for the Teaspoons UI: https://github.com/DataBiosphere/terra-ui/pull/5335
https://broadworkbench.atlassian.net/browse/TSPS-510
=> [TSPS-510] Add pipeline quota settings to getPipelineDetails

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java
Returns the version of the pipeline used for a particular pipeline run.
Used in https://github.com/DataBiosphere/terra-ui/pull/5341
https://broadworkbench.atlassian.net/browse/TSPS-519
=> [TSPS-519] Return pipeline version in getAllPipelineRuns response

ui/allofus-anvil-imputation/index.html
Queuing this up to deploy once we go live on August 25th.
* Updates language to "Beta is now available"
* "Get started" links to documentation home
Before:
After:
https://broadworkbench.atlassian.net/browse/TSPS-573
=> [TSPS-573] Update language on marketing website for service launch

.dockstore.yml
Casing issue with file path to beagle qc empty wdl
https://broadworkbench.atlassian.net/browse/TSPS-568
=> TSPS-568 update dockstore path for beagle qc empty wdl
