README.md, scripts/write-config.sh
This PR adds information to the README to help a developer who's new to the project get started. This includes requirements for programs that must be installed on the dev's local machine, as well as instructions for getting the service running locally.
We also needed to update the docker image used to access vault to make it compatible to be run on M1 machines (specifically: use an ARM-compatible build), per a recommendation from DevOps.
=> [TSPS-7] README updates for new developers

README.md
Architecture doc is still in progress but it's now linked in the repo README
=> [TSPS-14] add links to architecture docs to README

.github/workflows/tag-publish.yml
This PR includes changes prescribed by the [DevOps documentation](https://docs.google.com/document/d/1lkUkN2KOpHKWufaqw_RIE7EN3vN4G2xMnYBU83gi8VA/edit#) for deploying to dev using Sherlock.
We have already enabled the Sherlock SA on this app ([terraform-ap-deployments PR here](https://github.com/broadinstitute/terraform-ap-deployments/pull/950)), so the remaining step is to adjust our `tag-publish.yml` github workflow to call Sherlock. Per the documentation, I used the [corresponding TPS update](https://github.com/DataBiosphere/terra-policy-service/pull/37/commits/a97301a67a8fa07916ea02a09a515e6815de2be8) as a model.
=> [TSPS-20] Use Sherlock for dev deployments

service/src/main/java/bio/terra/pipelines/db/PipelinesDao.java, service/src/main/java/bio/terra/pipelines/db/exception/PipelineNotFoundException.java, service/src/main/java/bio/terra/pipelines/service/JobsService.java, service/src/main/java/bio/terra/pipelines/service/PipelinesService.java, service/src/test/java/bio/terra/pipelines/controller/PublicApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/SwaggerControllerTest.java, service/src/test/java/bio/terra/pipelines/db/PipelinesDaoTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/testutils/BaseTest.java, service/src/test/java/bio/terra/pipelines/testutils/BaseUnitTest.java
This PR ensures that when a new job request is made, the `pipelineId` in the request does exist (in the pipelines db table). If the provided `pipelineId` does not exist, we throw a 404 Pipeline not found error and return it to the user.
=> [TSPS-8] Validate job request (check for existing pipelineId)

service/src/main/java/bio/terra/pipelines/App.java, service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java
This PR processes the Optional object returned by timeCompleted in the getJob(s) responses into a null rather than a string "Optional.empty"
I edited the objectMapper bean in App.java to remove a line that removes null values from API responses; we prefer to include `"timeCompleted": null` in the response rather than remove the "timeCompleted" field entirely.
=> [TSPS-11] format empty timeCompleted to null in API response

service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java, service/src/main/java/bio/terra/pipelines/db/DbJob.java, service/src/main/java/bio/terra/pipelines/db/JobsDao.java, service/src/main/java/bio/terra/pipelines/service/JobsService.java, service/src/main/java/bio/terra/pipelines/service/model/Job.java, service/src/test/java/bio/terra/pipelines/controller/JobsControllerTest.java
this PR ensures that timestamps are stored in UTC and returned by APIs in UTC. we do this by using `Instant` rather than `Timestamp`, as the former enforces UTC.
=> [TSPS-12] store and return timestamps with UTC timezone

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java, service/src/main/java/bio/terra/pipelines/service/JobsService.java, service/src/main/java/bio/terra/pipelines/service/PipelinesService.java, service/src/test/java/bio/terra/pipelines/controller/JobsControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java
This PR:
- changes the PipelinesService method from `validatePipeline()` (throwing an exception if pipelineId not found) to `pipelineExists()` (returning a boolean)
- moves the validation step to call `pipelineExists()` from JobsService to JobsApiController
- updates PipelinesService tests for `validatePipeline()`
- DOES NOT include testing of validation in JobsApiController - this should be added in TSPS-27
Note - we probably want to invoke validatePipeline() in the other pipelines API requests - made TSPS-33 to do that
=> [TSPS-31] refactor pipelineId check to be called from controller layer

service/build.gradle, service/src/main/java/bio/terra/pipelines/db/JobsDao.java, service/src/main/resources/application.yml, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20221025.yaml, service/src/main/resources/db/changesets/20221128.yaml, service/src/main/resources/db/changesets/20230324-testdata.yaml, service/src/test/java/bio/terra/pipelines/db/BaseDaoTest.java, service/src/test/java/bio/terra/pipelines/db/JobsDaoTest.java, service/src/test/resources/application-test.yml
Testing writing records, getting duplicate entry errors, and ensuring that record for different users are properly isolated when we request them.
Also required changing the config some to allow for dao testing.  
Db changes 
- added in hibernate h2 in-memory database to the test config to allow for dao testing that doesn't touch the main db.
- Schema updated for both table to convert primary id to varchar(50) instead of text
- Liquibase now has contexts, allowing it to inserting test rows conditionally.  A new changlog contains jobs rows for testing
JobsDao has been slightly updated.  It now searches for a reference to the primary key "(job_id)" instead of matching on a long block of text, as the exact text varies between databases (and thus between postgres and the h2 instance used in …
=> [Tsps-30] test coverage for jobs dao

service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java
This PR adds a test for getPipelines() in PipelinesService
In the process, I also refactor some variables to MockMvcUtils that are likely to be reused elsewhere (TSPS-25)
=> [TSPS-28] add test for getPipelines() in PipelinesService

service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20230427.yaml
I got rid of the `text` type in the jobs and pipelines tables.  I used an upper bound of 50 for the main ids, an upper bound of 200 for display names and versions, and a generous upper bound of 1000 for freeform text fields like status and description.  This should give us plenty of room in the fields, and we can always tweak the values later if they cause problems (or trim them down, if we see that they are too generous.
=> Updating db types

.github/workflows/tag-publish.yml
Update TSPS's tag-publish workflow to publish container images from PRs, and also report them to Sherlock. This will allow TSPS devs to leverage Beehive's "deploy from a PR branch feature".
PR container image versions will consist of the next semver, suffixed with the git commit. (eg. `1.2.3-5e99528`).
I've successfully deployed images from this PR to my BEE (version `0.0.37-143e6b2` was built in [this GHA run]
=> [TSPS-97] Update tag-publish workflow to publish container images from PRs

README.md, scripts/write-config.sh, service/build.gradle, service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java, service/src/main/java/bio/terra/pipelines/dependencies/leonardo/LeonardoService.java, service/src/main/java/bio/terra/pipelines/dependencies/sam/SamService.java, service/src/main/java/bio/terra/pipelines/retry/RetryLoggingListener.java, service/src/main/java/bio/terra/pipelines/service/ImputationService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/controller/JobsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/dependencies/leonardo/LeonardoServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/sam/SamServiceTest.java, service/src/test/java/bio/terra/pipelines/service/ImputationServiceMockTest.java
Changing our usage of the leonardo client to use the google default credentials available instead of user credentials.  These can be supplied manually when developing and will be provided as part of the deployment in live environments
https://broadworkbench.atlassian.net/browse/TSPS-100
=> TSPS-100 add logic to use service account credentials when talking to leonardo

.github/workflows/tag-publish.yml
Its useful to also have a link to the PR/commit that corresponds to the failed publish action. This is what it looks like now
Before
After
Is it better or worse?
N/A
=> Update publish image github action slack message

service/build.gradle, service/src/main/java/bio/terra/pipelines/app/common/MetricsUtils.java, service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/common/MetricsUtilsTest.java
adding the instrumentation to connect metrics to prometheus by adding in actuator and exporting a count metric for pipelines run.  We'll want to have a discussion for what other product level metrics we want to track but just putting this one in as a test for now. This will need to go with a infrastructure helmchart change in order to get metrics to show up in a grafana dashboard.
screenshot of metric being tracked in my local server
https://broadworkbench.atlassian.net/browse/TSPS-102
=> TSPS-102 add instrumentation of prometheus metrics

service/build.gradle, service/src/main/java/bio/terra/pipelines/app/configuration/external/CbasConfiguration.java, service/src/main/java/bio/terra/pipelines/app/configuration/internal/RetryConfiguration.java, service/src/main/java/bio/terra/pipelines/dependencies/cbas/CbasClient.java, service/src/main/java/bio/terra/pipelines/dependencies/cbas/CbasService.java, service/src/main/java/bio/terra/pipelines/dependencies/cbas/CbasServiceApiException.java, service/src/main/java/bio/terra/pipelines/dependencies/cbas/CbasServiceException.java, service/src/main/java/bio/terra/pipelines/dependencies/leonardo/LeonardoService.java, service/src/main/java/bio/terra/pipelines/service/ImputationService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/configuration/external/CbasConfigurationTest.java, service/src/test/java/bio/terra/pipelines/configuration/external/SamConfigurationTest.java, service/src/test/java/bio/terra/pipelines/dependencies/cbas/CbasClientTest.java, service/src/test/java/bio/terra/pipelines/dependencies/cbas/CbasServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/leonardo/LeonardoServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/wds/WdsClientTest.java, service/src/test/java/bio/terra/pipelines/dependencies/wds/WdsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/ImputationServiceMockTest.java, service/src/test/resources/application-test.yml
This adds the ability to interact with the cbas client for a given workspace.  Currently only added the function to list all methods available.  Future work will add more functions as needed
https://broadworkbench.atlassian.net/browse/TSPS-138
=> TSPS-138 add cbas client integration

service/src/test/java/bio/terra/pipelines/controller/JobApiUtilsTest.java, service/src/test/java/bio/terra/pipelines/controller/JobsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java, service/src/test/java/bio/terra/pipelines/testutils/StairwayTestUtils.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
Added a test class for JobApiUtils, and in the process refactored some commonly used test variables and methods into StairwayTestUtils.
https://broadworkbench.atlassian.net/browse/TSPS-150
=> TSPS-150 add tests for JobApiUtils

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/configuration/external/IngressConfiguration.java, service/src/main/java/bio/terra/pipelines/app/controller/JobApiUtils.java, service/src/main/java/bio/terra/pipelines/app/controller/JobsApiController.java, service/src/main/java/bio/terra/pipelines/app/controller/PipelinesApiController.java, service/src/main/java/bio/terra/pipelines/dependencies/stairway/JobMapKeys.java, service/src/main/java/bio/terra/pipelines/dependencies/stairway/JobService.java, service/src/main/java/bio/terra/pipelines/service/ImputationService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/configuration/external/IngressConfigurationTest.java, service/src/test/java/bio/terra/pipelines/controller/JobApiUtilsTest.java, service/src/test/java/bio/terra/pipelines/controller/JobsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java, service/src/test/java/bio/terra/pipelines/dependencies/cbas/CbasClientTest.java, service/src/test/java/bio/terra/pipelines/dependencies/leonardo/LeonardoClientTest.java, service/src/test/java/bio/terra/pipelines/dependencies/sam/SamClientTest.java, service/src/test/java/bio/terra/pipelines/dependencies/stairway/JobServiceMockTest.java, service/src/test/java/bio/terra/pipelines/dependencies/stairway/JobServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/wds/WdsClientTest.java, service/src/test/java/bio/terra/pipelines/service/ImputationServiceMockTest.java, service/src/test/java/bio/terra/pipelines/service/ImputationServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceMockTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/RunImputationJobFlightTest.java, service/src/test/java/bio/terra/pipelines/testutils/StairwayTestUtils.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java, service/src/test/resources/application-test.yml
- Add GET {pipelineName}/result/{jobId} endpoint
- This endpoint returns a CreatedJobResponse object that always includes a JobReport and depending on status returns an ErrorReport (if the job failed) or a PipelineOutput (if the job succeeded)
- changed the PipelineOutput format to String (this will likely be the path to the result workspace, but TBD)
- Add functionality to generate and return the ResultURL in the JobReport; the GET jobs/{jobid} endpoint now returns a JobReport that includes this URL
e.g. response to a createJob request is now
```
{
"jobReport": {
"id": "faf85f64-5717-4562-b3fc-2c963f66afa6",
"description": "string",
"status": "RUNNING",
"statusCode": 202,
"submitted": "2024-02-12T17:08:32.537386Z",
"resultURL": "http://localhost:8080/api/pipelines/v1alpha1/imputation_mini …
```
=> TSPS-135 add the get result endpoint

service/build.gradle, service/src/main/java/bio/terra/pipelines/app/StartupInitializer.java, service/src/main/java/bio/terra/pipelines/app/configuration/external/SentryConfiguration.java, service/src/main/java/bio/terra/pipelines/app/controller/GlobalExceptionHandler.java, service/src/main/java/bio/terra/pipelines/app/controller/PipelinesApiController.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/configuration/internal/StairwayDatabaseConfigurationTest.java, service/src/test/resources/application-test.yml
To satisy the requirement for Production Readiness section M8, we need to send our exceptions to sentry for monitoring puproses. The work was already done to set up our dashboard and make sentry available to us.  This PR introduces sentry to the service and logs all 5** exceptions we generate to sentry for monitoring
This change has to go along with https://github.com/broadinstitute/terra-helmfile/pull/5103
https://broadworkbench.atlassian.net/browse/TSPS-172
=> log 5** exceptions to sentry

service/build.gradle
We have several security alerts for postgresql 42.3.3. This ticket upgrades that package to 42.3.9, which is the safe version per defectdojo, e.g. (note you need to be on VPN to see these pages)
- critical: https://defectdojo.dsp-appsec.broadinstitute.org/finding/188673
- high: https://defectdojo.dsp-appsec.broadinstitute.org/finding/188689 
Did manual integration test in my bee, everything apparently working fine.
This PR only partially addresses the work in this ticket: https://broadworkbench.atlassian.net/browse/TSPS-23
=> [TSPS-23] third party dependency security finding: postgresql:42.3.3 -> 42.3.9

service/src/main/java/bio/terra/pipelines/app/common/MetricsUtils.java, service/src/main/java/bio/terra/pipelines/app/controller/PipelinesApiController.java, service/src/main/java/bio/terra/pipelines/stairway/WriteJobToDbStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationJobFlight.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/common/MetricsUtilsTest.java, service/src/test/java/bio/terra/pipelines/stairway/WriteJobToDbStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/RunImputationJobFlightTest.java
We want to be able to create a grafana dashboard that tracks API metrics and this should enable that to be possible.
Here is the dashboard - https://grafana.dsp-devops.broadinstitute.org/d/3VhQ1_0Sz/tsps?orgId=1
example of the failed imputation workflow count being recorded in our prometheus endpoint
https://broadworkbench.atlassian.net/browse/TSPS-127
=> Enable metrics sent to prometheus for api latency metrics

service/src/main/resources/application.yml
We deployed a protected workspace in dev to use for our deployment there.  Our application.yml defaults to dev so just updating the value to match.
https://broadworkbench.atlassian.net/browse/TSPS-182
Successful run in the new workspace
=> TSPS-182 update default imputation workspaceId to match dev protected workspae

buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.pipelines.java-common-conventions.gradle, service/build.gradle
Per latest sourceclear scan (screenshot in Jira ticket), the following updates:
- logback-classic -> now 1.4.14 (via spring boot -> 3.2.3)
- logback-core -> now 1.4.14 (via spring boot -> 3.2.3)
- postgresql -> now 42.6.1 (direct dependency)
- snakeyaml -> now 2.2 (via terra-common-lib -> 1.0.9)
The following are supposedly brought in by terra-common-lib but don't show up on insightDependency. 
- commons-compress* - [TCL updated this to 1.26.0](https://github.com/DataBiosphere/terra-common-lib/blob/develop/build.gradle#L134)
Unclear whether these changes will also upgrade bouncycastle, since this also doesn't show up on insightDependency.
https://broadworkbench.atlassian.net/browse/TSPS-23
=> [TSPS-23] Third party dependency security updates

buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.pipelines.java-common-conventions.gradle, client/swagger.gradle, service/build.gradle, service/src/test/java/bio/terra/pipelines/dependencies/sam/SamServiceTest.java
Retrying with the addition of [some fixes courtesy Olivia/WSM](https://github.com/DataBiosphere/terra-workspace-manager/pull/1666/files)
Per latest sourceclear scan (screenshot in Jira ticket), the following updates:
- logback-classic -> now 1.4.14 (via spring boot -> 3.2.3)
- logback-core -> now 1.4.14 (via spring boot -> 3.2.3)
- postgresql -> now 42.6.1 (direct dependency)
- snakeyaml -> now 2.2 (via terra-common-lib -> 1.0.9)
The following are supposedly brought in by terra-common-lib but don't show up on insightDependency. 
- commons-compress* - [TCL updated this to 1.26.0](https://github.com/DataBiosphere/terra-common-lib/blob/develop/build.gradle#L134)
Unclear whether these changes will also upgrade bouncycastle, since this also doesn't show up on insightDependency. …
=> TSPS-23 Third party dependency security upgrades: logback-classic, logback-core, snakeyaml, postgresql, commons-compress

buildSrc/src/main/groovy/bio.terra.pipelines.java-common-conventions.gradle, service/build.gradle
See https://broadworkbench.atlassian.net/browse/PF-3000 and https://github.com/DataBiosphere/terra-common-lib/pull/167
Tested in my BEE; turned on the IN_KUBERNETES flag and reproduced the "KubePodListener caught exception: java.lang.IllegalArgumentException: The field `volumes` in the JSON string is not defined in the `V1NamespaceSpec` properties" on main; these errors went away (and the service continued to function) when testing on this branch.
https://broadworkbench.atlassian.net/browse/TSPS-202
=> TSPS-202 upgrade to TCL version 1.1.4 to resolve k8s breaking change

README.md, common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/configuration/internal/ImputationConfiguration.java, service/src/main/java/bio/terra/pipelines/app/controller/AdminApiController.java, service/src/main/java/bio/terra/pipelines/app/controller/PipelineApiUtils.java, service/src/main/java/bio/terra/pipelines/app/controller/PipelinesApiController.java, service/src/main/java/bio/terra/pipelines/db/entities/Pipeline.java, service/src/main/java/bio/terra/pipelines/dependencies/sam/SamClient.java, service/src/main/java/bio/terra/pipelines/dependencies/sam/SamService.java, service/src/main/java/bio/terra/pipelines/service/ImputationService.java, service/src/main/java/bio/terra/pipelines/service/PipelinesService.java, service/src/main/resources/application.yml, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240417_add_workspace_id_to_pipelines.yaml, service/src/test/java/bio/terra/pipelines/controller/AdminApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiUtilsTest.java, service/src/test/java/bio/terra/pipelines/dependencies/sam/SamServiceTest.java, service/src/test/java/bio/terra/pipelines/service/ImputationServiceMockTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
In order to make e2e testing easier (and for generally more flexibility in running tsps) we want to add an admin endpoint that allows an admin user to update the workspace id for a given pipeline.
https://broadworkbench.atlassian.net/browse/TSPS-224
=> TSPS-224 add admin endpoint to be able to update workspace id for a pipeline

.github/workflows/run-e2e-tests.yaml
I think we're separating the commands of the init-params step incorrectly.  I think it should be a `|` instead of a `>` https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
No ticket explicitly but related to https://broadworkbench.atlassian.net/browse/TSPS-124
=> update params step in e2e workflow to get bee-destroy step to always run

buildSrc/src/main/groovy/bio.terra.pipelines.java-common-conventions.gradle, service/build.gradle
Upgrade TCL to version 1.1.11-SNAPSHOT, which brings in bouncycastle 1.78 to resolve the high security finding
https://broadworkbench.atlassian.net/browse/TSPS-234
=> TSPS-234 upgrade TCL to get bouncycastle upgrade to v1.78

service/src/main/java/bio/terra/pipelines/dependencies/cbas/CbasServiceApiException.java, service/src/main/java/bio/terra/pipelines/dependencies/cbas/CbasServiceException.java, service/src/main/java/bio/terra/pipelines/dependencies/common/DependencyNotAvailableException.java, service/src/main/java/bio/terra/pipelines/dependencies/leonardo/AppUtils.java, service/src/main/java/bio/terra/pipelines/dependencies/leonardo/LeonardoServiceApiException.java, service/src/main/java/bio/terra/pipelines/dependencies/leonardo/LeonardoServiceException.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/CheckCbasHealthStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/CheckLeonardoHealthStep.java, service/src/test/java/bio/terra/pipelines/dependencies/wds/WdsServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/StairwayExceptionSerializerTest.java
These 3 exceptions are now deserializable when they are thrown in a flight (you can see in the test I changed that the exception we were expecting to fail now succeeds so I changed it to an exception that isnt thrown at all)
https://broadworkbench.atlassian.net/browse/TSPS-231
=> TSPS-231 update exceptions thrown in flight to be deserializable

pipelines/testing/CompareVcfs.wdl, wdls/imputation/VcfChecker.wdl
As part of the work to making beagle determinstic (work done in https://github.com/broadinstitute/warp/pull/1285) we wanted to have wdl that we could pass in two vcfs to and verify that they are in fact the same.
This is the run of this wdl that verifies outputs from two different runs of the new beagle wdl were in fact the same - https://bvdp-saturn-dev.appspot.com/#workspaces/tsps_dev_bp_02_01_2024_v1/imputation-pipeline-testing-03-07-2024/workflows-app/submission-history/14873abd-23c3-4df9-81b8-00d813fd21fe
A run to make sure the workflow does fail when the two files are not the same - https://bvdp-saturn-dev.appspot.com/#workspaces/tsps_dev_bp_02_01_2024_v1/imputation-pipeline-testing-03-07-2024/workflows-app/submission-history/d96627a1-b0eb-4eb9-95ba-841ca19ff2c3 …
=> TSPS-221 add checker wdl to test if two vcfs are the same

pipelines/testing/ImputationBeagleEmpty.wdl, service/src/main/java/bio/terra/pipelines/app/configuration/external/CbasConfiguration.java, service/src/main/java/bio/terra/pipelines/common/utils/FlightBeanBag.java, service/src/main/java/bio/terra/pipelines/dependencies/cbas/CbasClient.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationJobFlight.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/SubmitCromwellRunSetStep.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/common/utils/FlightBeanBagTest.java, service/src/test/java/bio/terra/pipelines/configuration/external/CbasConfigurationTest.java, service/src/test/java/bio/terra/pipelines/dependencies/cbas/CbasServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/SubmitCromwellRunSetStepTest.java, service/src/test/resources/application-test.yml
We don't want to use call caching for now. 
Also, remove outputs that are no longer in the real WDL now that https://github.com/broadinstitute/warp/pull/1288 is merged.
Tested locally:
=> don't call cache cbas submissions, remove outputs from empty WDL

service/src/main/java/bio/terra/pipelines/app/controller/GlobalExceptionHandler.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/AddWdsRowStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/CheckCbasHealthStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/CheckLeonardoHealthStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/CheckWdsHealthStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/CompletePipelineRunStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/GetAppUrisStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/PollCromwellRunSetStatusStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/PrepareImputationInputsStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationJobFlight.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/SubmitCromwellRunSetStep.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/AddWdsRowsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/CheckCbasHealthStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/CheckWdsHealthStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/CompletePipelineRunStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/GetAppUrisStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/PollCromwellRunSetStatusStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/PrepareImputationInputsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/SubmitCromwellRunSetStepTest.java
- TSPS-257: add Stairway retry logic to steps that call CBAS or WDS
- TSPS-243: filter out NoResourceFoundExceptions from Sentry (still will be logged as errors, plus a warning that it wasn't sent to sentry)
https://broadworkbench.atlassian.net/browse/TSPS-257
https://broadworkbench.atlassian.net/browse/TSPS-243
=> TSPS-257, TSPS-243 add Stairway retries to WDS and CBAS steps, also Don't alert Sentry for NoResourceFoundException

service/src/main/java/bio/terra/pipelines/common/utils/PipelineVariableTypesEnum.java, service/src/main/java/bio/terra/pipelines/db/entities/BasePipelineVariableDefinition.java, service/src/main/java/bio/terra/pipelines/db/entities/PipelineInputDefinition.java, service/src/main/java/bio/terra/pipelines/db/entities/PipelineOutputDefinition.java, service/src/main/java/bio/terra/pipelines/db/entities/converters/PipelineInputTypeConverter.java, service/src/main/java/bio/terra/pipelines/db/entities/converters/PipelineVariableTypeConverter.java, service/src/main/java/bio/terra/pipelines/service/PipelinesService.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/PrepareImputationInputsStep.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240716_add_file_suffix_to_input_defs_and_update_FILE_types.yaml, service/src/test/java/bio/terra/pipelines/common/utils/PipelineVariableTypesEnumTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceDatabaseTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/PrepareImputationInputsStepTest.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
- rename `PipelineInputTypesEnum` to `PipelineVariableTypesEnum`
- use it in base `BasePipelineVariableDefinition` class, so used for both `PipelineInputDefinition` and `PipelineOutputDefinition`
- add a `file_suffix` field to pipeline_input_definitions table in the db, change existing `VCF` types to `FILE`s and add `".vcf.gz"` as the file suffix for those
- refactor enum values `VCF` -> `FILE` and `VCF_ARRAY` -> `FILE_ARRAY`; update the `validate()` method to check the fileSuffix for FILE and FILE_ARRAY types
https://broadworkbench.atlassian.net/browse/TSPS-268
=> TSPS-268 unify PipelineVariableTypesEnum and associated changes

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/main/java/bio/terra/pipelines/common/utils/pagination/CursorBasedPageable.java, service/src/main/java/bio/terra/pipelines/common/utils/pagination/FieldEqualsSpecification.java, service/src/main/java/bio/terra/pipelines/common/utils/pagination/PageResponse.java, service/src/main/java/bio/terra/pipelines/common/utils/pagination/PageSpecification.java, service/src/main/java/bio/terra/pipelines/db/entities/Pipeline.java, service/src/main/java/bio/terra/pipelines/db/repositories/PipelineRunsRepository.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/test/java/bio/terra/pipelines/common/utils/pagination/CursorBasedPageableTest.java, service/src/test/java/bio/terra/pipelines/common/utils/pagination/FieldEqualsSpecificationTest.java, service/src/test/java/bio/terra/pipelines/common/utils/pagination/PageSpecificationTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java
this addes a getPipelineRuns endpoint that allows a user to query for the pipelineRuns they've created in a cursor based  paginated way.  This will return the most recent runs first followed by older runs.  Currently there is no extra filtering on type of pipeline but that can be done in the future if the UI/UX requires it but for now it will just return all pipelines associated to the user making the request.
https://broadworkbench.atlassian.net/browse/TSPS-262
=> TSPS-262 paginated get pipeline runs endpoint

.dockstore.yml
In order to import workflows into GCP Terra workspaces, they need to be either in the Methods Repo (Agora) or Dockstore. Dockstore allows automatic updates via github, so that's what we're doing. This PR adds the required .dockstore.yml file to specify the workflows to sync in Dockstore.
=> Add WDL pipelines to Dockstore

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/AdminApiController.java, service/src/main/java/bio/terra/pipelines/db/entities/Pipeline.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/main/java/bio/terra/pipelines/service/PipelinesService.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/steps/gcp/SubmitCromwellSubmissionStep.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240820_add_workspace_storage_container_url.yaml, service/src/test/java/bio/terra/pipelines/controller/AdminApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
Rather than hardcoding the control workspace's storage container (bucket) url, we now store it in the db and can update it via an admin API.
We require all the workspace values to be provided in the admin update api to be not null.
Also an add-on update to https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/112 now that we have an "emptyWDL" dev control workspace to use that has the correct WDL method name.
https://broadworkbench.atlassian.net/browse/TSPS-300
=> TSPS-300 store control workspace storage container url in db, update via admin api

service/src/main/java/bio/terra/pipelines/common/utils/FileUtils.java, service/src/main/java/bio/terra/pipelines/dependencies/gcs/GcsService.java, service/src/main/java/bio/terra/pipelines/dependencies/rawls/RawlsService.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpJobFlight.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/steps/gcp/FetchOutputsFromDataTableStep.java, service/src/test/java/bio/terra/pipelines/common/utils/FileUtilsTest.java, service/src/test/java/bio/terra/pipelines/dependencies/gcs/GcsServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/rawls/RawlsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpFlightTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/FetchOutputsFromDataTableStepTest.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
We now return signed GET (read-only) urls for pipeline run outputs, when the user calls get pipeline run result.
Added logic to redact the signature string from the signed url when we log its creation (for both PUT and GET signed urls).
To do this, we had to add two steps to the GCP flight:
- FetchOutputsFromDataTableStep (brand new step, GCP correlary of the Azure FetchOutputsFromWdsStep)
- CompletePipelineRunStep (reused existing step)
https://broadworkbench.atlassian.net/browse/TSPS-306
=> TSPS-306 getResult returns signed urls for all outputs

rawls-client/swagger.gradle, service/src/main/java/bio/terra/pipelines/dependencies/rawls/RawlsClient.java, service/src/main/java/bio/terra/pipelines/dependencies/rawls/RawlsService.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpJobFlight.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationJobFlightMapKeys.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/steps/gcp/SubmitCromwellSubmissionStep.java, service/src/test/java/bio/terra/pipelines/dependencies/rawls/RawlsClientTest.java, service/src/test/java/bio/terra/pipelines/dependencies/rawls/RawlsServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/PrepareImputationInputsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/SubmitCromwellSubmissionStepTest.java, service/src/test/java/bio/terra/pipelines/testutils/StairwayTestUtils.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
We want to make sure we are using the correct wdl and inputs when submitting our pipelines.  This PR adds the logic to the submission step in the flight make this possible.
Do we think this is too much to do in one step?
https://broadworkbench.atlassian.net/browse/TSPS-303
=> TSPS-303 validate method config and update if needed

service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/main/java/bio/terra/pipelines/common/utils/CommonPipelineRunStatusEnum.java, service/src/main/java/bio/terra/pipelines/db/entities/PipelineRun.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationAzureJobFlight.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpJobFlight.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/steps/PrepareImputationInputsStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/steps/azure/CheckLeonardoHealthStep.java, service/src/main/resources/application.yml, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240911_remove_isSuccess.yaml, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/CompletePipelineRunStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/PrepareImputationInputsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/CheckLeonardoHealthStepTest.java
Previously we were not updating the final status of a PipelineRun in the PipelineRuns table, meaning when a user retrieves all their PipelineRuns, they only see status RUNNING.
We now update the status to SUCCEEDED in the (final) CompletePipelineRunStep, and we update status to FAILED in the undo step of (first step in GCP and Azure flights) PrepareImputationInputsStep.
GET pipelineruns endpoint now returns:
```{
"pageToken": "IyMjNyMjIyAtIDIwMjQtMDktMTBUMTY6MTE6MDcuMDAzMjUw",
"results": [
{
"jobId": "11112115-5717-4562-b3fc-2c963f66afa6",
"status": "FAILED",
"description": "test finalize FAILED status"
},
{
"jobId": "11112114-5717-4562-b3fc-2c963f66afa6",
"status": "SUCCEEDED",
"description": "test finalize SUCCEEDED status"
},
```
https://broadworkbench.atlassian.net/browse/TSPS-310 …
=> TSPS-310 final PipelineRun status persisted to PipelineRuns table

service/src/main/java/bio/terra/pipelines/db/entities/BasePipelineVariableDefinition.java, service/src/main/java/bio/terra/pipelines/db/entities/PipelineInputDefinition.java, service/src/main/java/bio/terra/pipelines/db/entities/PipelineOutputDefinition.java, service/src/test/java/bio/terra/pipelines/controller/AdminApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/JobsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java, service/src/test/java/bio/terra/pipelines/db/entities/PipelineInputDefinitionTest.java, service/src/test/java/bio/terra/pipelines/db/entities/PipelineOutputDefinitionTest.java, service/src/test/java/bio/terra/pipelines/dependencies/cbas/CbasServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/gcs/GcsServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/leonardo/LeonardoServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/sam/SamServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/stairway/JobServiceMockTest.java, service/src/test/java/bio/terra/pipelines/dependencies/wds/WdsServiceTest.java, service/src/test/java/bio/terra/pipelines/dependencies/workspacemanager/WorkspaceManagerServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/AddWdsRowsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/CheckCbasHealthStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/CheckWdsHealthStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/FetchOutputsFromWdsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/GetAppUrisStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/PollCromwellRunSetStatusStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/SubmitCromwellRunSetStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/AddDataTableRowStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/FetchOutputsFromDataTableStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/PollCromwellSubmissionStatusStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/SubmitCromwellSubmissionStepTest.java
I got rid of pretty much all of them and I probably went overboard with some tests because we dont need to test all arguments match EVERY single time but it was easier to copy paste once i was in there.  Especially for the methods that are testing for exceptions being thrown you can use `any()` cuz you don't really care.  Basically anytime you do a positive test it should try to not use `any()` as much as possible
https://broadworkbench.atlassian.net/browse/TSPS-316
=> TSPS-316 remove all unhelpful "any()" matchers from our tests

.github/workflows/run-e2e-tests.yaml
Successful run without specifying a wdl method version: https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/10948530034
https://broadworkbench.atlassian.net/browse/TSPS-280
=> TSPS-280 e2e test fix - auto-pull lastest git release tag if not specified

service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240923_update_input_defs_bucket_paths.yaml
Updating the default_value for service-provided input files to match the organization we want. This includes an `hg38` prefix for all, plus different intermediate "directory" files in some cases
Changes:
- geneticMapsPath
- old value: `/plink-genetic-maps/GRCh38_fixed/`
- new value: `/hg38/plink-genetic-maps/`
- refDict 
- old value: `/hg38/Homo_sapiens_assembly38.dict`
- new value: `/hg38/ref_dict/Homo_sapiens_assembly38.dict`
- referencePanelPathPrefix
- old value: `/hg38/1000G_HGDP_no_singletons_ref_panel/hgdp.tgp.gwaspy.merged.merged.AN_added.bcf.ac2`
- new value: `/hg38/ref_panels/1000G_HGDP_no_singletons/hgdp.tgp.gwaspy.merged.merged.AN_added.bcf.ac2`
Also performed the copy of these files in the dev bucket:
```
✗ gcloud storage ls …
```
=> Redefine service-provided input paths

service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/main/java/bio/terra/pipelines/common/utils/FlightBeanBag.java, service/src/main/java/bio/terra/pipelines/service/PipelineInputsOutputsService.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationAzureJobFlight.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpJobFlight.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationJobFlightMapKeys.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/steps/PrepareImputationInputsStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/steps/gcp/FetchOutputsFromDataTableStep.java, service/src/test/java/bio/terra/pipelines/common/utils/FlightBeanBagTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineInputsOutputsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/PrepareImputationInputsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/FetchOutputsFromDataTableStepTest.java, service/src/test/java/bio/terra/pipelines/testutils/StairwayTestUtils.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
The previous conversion from storageContainerUrl to storageContainerName caused a problem in PreparePipelineInputsStep since it expects that value to be the full Url. Here we add a value to the flight working map to specify the protocol to append to the storageContainerName.
Also did a refactor of a bunch of methods related to input and output formatting and generation into a new PipelineInputsOutputsService.
https://broadworkbench.atlassian.net/browse/TSPS-332
=> [TSPS-322] make explicit storage container url in PrepareImputationInputsStep

service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240925_update_ref_panel_prefix_input.yaml
We're looking for the wrong files. Running the pipeline gave errors like this: 
`FileNotFoundException: gs://fc-secure-10efd4d7-392a-4e9e-89ea-d6629fbb06cc/hg38/ref_panels/1000G_HGDP_no_singletons/hgdp.tgp.gwaspy.merged.merged.AN_added.bcf.ac2.chr1.bed`
Whereas the files are actually located at `gs://fc-secure-10efd4d7-392a-4e9e-89ea-d6629fbb06cc/hg38/ref_panels/1000G_HGDP_no_singletons/hgdp.tgp.gwaspy.AN_added.bcf.ac2.chr1.bed`
i.e. we need the ref panel prefix default_value to be updated from `/hg38/ref_panels/1000G_HGDP_no_singletons/hgdp.tgp.gwaspy.merged.merged.AN_added.bcf.ac2` to `/hg38/ref_panels/1000G_HGDP_no_singletons/hgdp.tgp.gwaspy.AN_added.bcf.ac2`
none
=> fix ref panel prefix

.dockstore.yml, pipelines/imputation/scientificValidation/README.md, pipelines/imputation/scientificValidation/ReshapeReferencePanel.wdl, pipelines/imputation/scientificValidation/SubsetVcfByBedFile.wdl
We want to use this wdl for scientific validation of the refernece panel.  We will mask wgs samples down to an array build's sites and then impute and we shoudl get something close to the original wgs sample
Example of workflow running - https://bvdp-saturn-dev.appspot.com/#workspaces/general-dev-billing-account/tsps_gcp_scratch_space_mma/job_history/dd9e56bd-63d6-43d4-bd9f-93caf91dcdae
https://broadworkbench.atlassian.net/browse/TSPS-326
=> TSPS-326 add wdl to mask or subset a vcf given a bed file

.dockstore.yml, pipelines/imputation/simulatedData/CreateImputationRefPanelBeagle.wdl, pipelines/imputation/simulatedData/README.md
small update to the create ref panel wdl to be easier to use and get dockstore working correctly with all of our wdls
None
=> try to make dockstore happy

.dockstore.yml, pipelines/imputation/scientificValidation/README.md, pipelines/imputation/scientificValidation/SubsetVcfByBedFile.wdl, pipelines/imputation/scientificValidation/UpdateVcfHeaderContigs.wdl
WDL updates to SubsetVcfByBedFile (masking wdl) to allow subsetting by samples.
Add new WDL: UpdateVcfDictionaryHeader, to update a VCF's headers to include the proper contigs as specified by a reference dictionary.
https://broadworkbench.atlassian.net/browse/TSPS-328
=> TSPS-328 add optional samples subselection to SubsetVcfByBedFile WDL

pipelines/imputation/testing/CompareVcfs.wdl
When trying to verify if the results were the same between the 5MB and 2MB overlap values, the task failed due to disk.  This  allowed it to succeed
failed - https://bvdp-saturn-dev.appspot.com/#workspaces/teaspoons-imputation-dev/teaspoons_imputation_dev_control_workspace_20240726/job_history/b53431c5-4c52-4efe-bb2d-68b266fd565b
succeeded - https://bvdp-saturn-dev.appspot.com/#workspaces/teaspoons-imputation-dev/teaspoons_imputation_dev_control_workspace_20240726/job_history/90342454-2886-4d9e-9669-333df0c022d4
https://broadworkbench.atlassian.net/browse/TSPS-343
=> TSPS-343 increase disk for comparevcfs task 

pipelines/imputation/scientificValidation/UpdateVcfDictionaryHeader.wdl
Make reheadering of VCFs with correct sequence dictionary more efficient, since we'll need to run it on the AoU+AnVIL reference panel VCFs and that will take a long time.
Changes:
- extract the header, fix it, then reheader the original, rather than fixing it in the original in one step
- use bcftools to create index instead of tabix
- add echos with dates for better progress tracking 
Some learnings about timing:
- the vast majority of this task is spent creating the index
- next longest step is localization of the files (1 hour for chr20 vcf)
Note we ran this with a monitoring script and found that the task was not close to using all the memory available (memory utilization did not exceed 11%), so we don't think an optimization there would help. We also weren't pegged on iops (didn't …
=> TSPS-342 Update reheader seq dict wdl for better efficiency

.github/workflows/workflow-tester.yml, service/src/main/java/bio/terra/pipelines/db/entities/PipelineQuota.java, service/src/main/java/bio/terra/pipelines/db/repositories/PipelineQuotasRepository.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20241030_add_pipeline_quotas.yaml
Starting off the quotas work, adding the pipeline_quotas table which will be used in future PRs flesh out the quota work
Not really bothering with tests here since there is no logic yet to really test
https://broadworkbench.atlassian.net/browse/TSPS-354
=> TSPS-354 add pipeline quotas table

.github/workflows/release-python-client.yml, .github/workflows/tag-publish.yml, README.md
Publish the thin (auto-generated) client to PyPi via GHA.
- PyPi project name: terra-scientific-pipelines-service-api-client
- PyPi package name: teaspoons_client
achieves part of https://broadworkbench.atlassian.net/browse/TSPS-348
=> TSPS-348 part one: Publish Python thin client 

.github/workflows/release-python-client.yml, .github/workflows/tag-publish.yml
Build the jar, docker, and python thin client off of the main branch as tagged by tag-job, rather than the latest main, which could have new commits after the tag was made.
https://broadworkbench.atlassian.net/browse/TSPS-367
=> TSPS-367 Use tag for builds

service/src/main/java/bio/terra/pipelines/common/utils/PipelinesEnum.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20240412-testdata.yaml, service/src/main/resources/db/changesets/20241106_array_imputation_rename.yaml, service/src/test/java/bio/terra/pipelines/common/MetricsUtilsTest.java, service/src/test/java/bio/terra/pipelines/controller/AdminApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiUtilsTest.java, service/src/test/java/bio/terra/pipelines/db/entities/UserQuotaTest.java, service/src/test/java/bio/terra/pipelines/dependencies/stairway/JobServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceDatabaseTest.java, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/RunImputationAzureFlightTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpFlightTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/PrepareImputationInputsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/AddWdsRowsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/azure/FetchOutputsFromWdsStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/FetchOutputsFromDataTableStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/steps/gcp/SubmitCromwellSubmissionStepTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java, service/src/test/java/bio/terra/pipelines/testutils/StairwayTestUtils.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
Updated the pipeline name `imputation_beagle` to `array_imputation`. Also updated that pipeline's description.
Tested locally, a new PipelineRun worked successfully.
This change is not backwards-compatible; old jobs run using `imputation_beagle` will no longer be accessible. This is acceptable since we're still only in dev and are about to wipe/migrate our database anyway.
Associated PR to update the e2e test: https://github.com/broadinstitute/dsp-reusable-workflows/pull/52
https://broadworkbench.atlassian.net/browse/TSPS-368
=> TSPS-368 Update imputation_beagle to array_imputation

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/QuotasController.java, service/src/main/java/bio/terra/pipelines/service/QuotasService.java, service/src/test/java/bio/terra/pipelines/controller/QuotasControllerTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java
This PR adds an API endpoint that allows the user to see their quota usage for a given pipeline
https://broadworkbench.atlassian.net/browse/TSPS-356
=> TSPS-356 add quotas controller with api to get quota for a pipeline

service/src/main/java/bio/terra/pipelines/common/utils/FlightBeanBag.java, service/src/main/java/bio/terra/pipelines/service/QuotasService.java, service/src/main/java/bio/terra/pipelines/stairway/FetchQuotaConsumedFromDataTableStep.java, service/src/main/java/bio/terra/pipelines/stairway/QuotaConsumedValidationStep.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/ImputationJobMapKeys.java, service/src/main/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpJobFlight.java, service/src/test/java/bio/terra/pipelines/common/utils/FlightBeanBagTest.java, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/FetchQuotaConsumedFromDataTableStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/PollQuotaConsumedSubmissionStatusStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/QuotaConsumedValidationStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/SubmitQuotaConsumedSubmissionStepTest.java, service/src/test/java/bio/terra/pipelines/stairway/imputation/RunImputationGcpFlightTest.java
This pr does a few things
* if the quota consumed for the current flight plus their aggregate quota consumed is above the users quota limit, we fail the flight and not submit the imputation wdl
* if the quota consumed for the current flight plus their aggregate quota consumed is below the users quota limit, we store the quota consumed for the current flight to the user quotas table
* in case the step is undo'd, we give back the user their quota consumed for the flight
https://broadworkbench.atlassian.net/browse/TSPS-361
=> TSPS-361 add quota consumed logic

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/AdminApiController.java, service/src/main/java/bio/terra/pipelines/app/controller/QuotasController.java, service/src/main/java/bio/terra/pipelines/service/QuotasService.java, service/src/main/java/bio/terra/pipelines/stairway/QuotaConsumedValidationStep.java, service/src/test/java/bio/terra/pipelines/controller/AdminApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/QuotasControllerTest.java, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/QuotaConsumedValidationStepTest.java
At some point we may want to increase a users quota above the default.  This admin endpoint makes it possible for us to do so if we want to.
https://broadworkbench.atlassian.net/browse/TSPS-357
=> TSPS-357 Add admin endpoint to get a user's quota and update their quota

service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20241121_remove_user_quota_pname_uk.yaml, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java
Fixing an issue that morgan found with the user_quotas table.  There is no reason for there to be a unique constraint on the pipeline name column of the user quotas table
added a test to make sure this is workign as intended
=> drop pipeline_name unique constraint from user_quotas table

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/main/java/bio/terra/pipelines/common/utils/CommonPipelineRunStatusEnum.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java
Fix an error in our openapi.yml as well as don't require the description field in the PipelineRun object returned by getAllPipelineRuns. This wasn't actually making the field required anyway in our response - the following is the response to getAllPipelineRuns *before* this change:
```
{
"pageToken": "IyMjNDEjIyMgLSAyMDI0LTExLTIwVDEzOjE5OjMxLjQ4MTc4NQ==",
"results": [
{
"jobId": "82d391bf-d5e7-49c9-819e-71b5b9584365",
"status": "SUCCEEDED",
"description": "local run for download testing second attempt"
},
{
"jobId": "6e99d57e-977b-4464-91f3-df7c8c5c4bf0",
"status": "PREPARING"
},
{
"jobId": "3582c093-5093-4193-b9e4-62c6334a62da",
"status": "PREPARING"
},
```
But making it not required allows the autogenerated Python client to accept this response rather than failing it on validation when …
=> TSPS-325 Support for adding more CLI commands

service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java
I dont this endpoint should actually return a successful response for PREPARING jobs because nothing has been run yet.  I think this is the best way to handle that scenario by guiding the user down the correct path.
https://broadworkbench.atlassian.net/browse/TSPS-381
=> TSPS-381 Address PREPARING job response for result endpoint 

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java
Note this does not change the result endpoint because that is being changed in https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/166 .  This PR also adds the pipeline name to the response of getAllPipelineRuns
https://broadworkbench.atlassian.net/browse/TSPS-382
=> TSPS-382 remove pipelineName from serveral APIs that dont need it

.github/workflows/tag-publish.yml
Want to release this to see what it does to the version endpoint response.  I think this will make it so all deployments, even local not have a `-VERSION` suffix which may not be what we want
https://broadworkbench.atlassian.net/browse/TSPS-362
=> TSPS-362 try removing VERSION_SUFFIX line from tag github step

.github/workflows/tag-publish.yml, service/src/main/resources/application.yml, service/src/test/java/bio/terra/pipelines/configuration/external/GcsConfigurationTest.java, service/src/test/java/bio/terra/pipelines/dependencies/gcs/GcsServiceTest.java
Reduce the duration of signed urls:
- put / upload: reduced from 24 hours to 8 hours
- get / download: reduced from 24 hours to 1 hour
Note that the user must simply begin the process (upload or download) within the active duration of the signed url; the operation does not need to complete in that time.
Also: changing our artifactory repo to `libs-release` rather than `libs-snapshot-local`
https://broadworkbench.atlassian.net/browse/TSPS-375
=> TSPS-375 reduce signed url durations

.github/workflows/tag-publish.yml, service/src/main/java/bio/terra/pipelines/app/controller/PublicApiController.java, service/src/main/resources/templates/index.html
Add a Content-Security-Policy header to swagger.
Turns out that a lot in the `index.html` file gets overridden (e.g. the title there is `Terra Scientific Pipelines Service Swagger UI` but the swagger page title is just `Terra Scientific Pipelines Service`); adding the content header directly to that html doesn't work. Adding it in the Controller works.
Run locally:
The CSP also appears on the openapi.yml response headers.
Also: again trying to fix our deployment by updating the artifactory repo to `libs-release-local`.
https://broadworkbench.atlassian.net/browse/TSPS-366
=> TSPS-366 Add Content-Security-Policy header to Swagger page

service/generators.gradle
Update swagger-ui-dist version from 4.18.1 -> 5.18.2 (latest version available), which apparently uses dompurify version 3.1.6. We wanted >= 2.5.0 to fix the vulnerability. 
Now http://localhost:8080/webjars/swagger-ui-dist/swagger-ui-bundle.js (when service run locally) includes 
```
if(DOMPurify.version="3.1.6",DOMPurify.removed=[],!o||!o.document||o.document.nodeType!==rt.document)return DOMPurify.isSupported=!1,DOMPurify
```
https://broadworkbench.atlassian.net/browse/TSPS-365
=> TSPS-365 Update swagger-ui-dist to latest version for dompurify vulnerability fix

service/src/main/java/bio/terra/pipelines/app/controller/PublicApiController.java, service/src/test/java/bio/terra/pipelines/controller/PublicApiControllerTest.java
Update CSP header on swagger to not break b2c auth.
Also remove the redirect on the root swagger page.
follow-on fix for https://broadworkbench.atlassian.net/browse/TSPS-366
=> TSPS-366 fix CSP header to work with b2c auth

service/src/main/java/bio/terra/pipelines/db/entities/PipelineRun.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java
API now returns timestamps with UTC indicated by final Z:
getAllResults:
```
{
"results": [
{
"jobId": "cab58b4f-fbcb-4088-82f6-72ab38d9e966",
"pipelineName": "array_imputation",
"status": "FAILED",
"description": "NA12878 renamedx50 local",
"timeSubmitted": "2024-12-04T18:54:25.153916Z",
"timeCompleted": "2024-12-04T18:55:14.506835Z"
}
]
}
```
get one result:
```
{
"jobReport": {
"id": "cab58b4f-fbcb-4088-82f6-72ab38d9e966",
"description": "NA12878 renamedx50 local",
"status": "FAILED",
"statusCode": 500,
"submitted": "2024-12-04T18:54:36.114917Z",
"completed": "2024-12-04T18:55:14.459730Z",
```
And confirmed that with this result, the CLI converts to the local time zone correctly.
```
✗ terralab jobs list
Job ID                                Pipeline Name     Status    Submitted …
```
=> TSPS-387 return UTC-formatted timestamps

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/main/java/bio/terra/pipelines/db/entities/PipelineRun.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
The job description for each pipeline run is technically required for the flight, which is created on pipeline run start, but it was onerous and causing other problems to have to supply it then rather than with all the other inputs on pipeline run prepare, so we moved it to the prepare endpoint.
Note: Once this is merged, will need to update this CLI PR with the new thin client version: https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/pull/20
Calling prepare with a description:
Description is optional:
Start doesn't take a description:
Note that if no description is provided, it's still not included in the get all pipeline runs response and the CLI still doesn't like it, so [this PR in the cli repo](https://github.com/DataBiosphere/terra-scientific-pipelines-service- …
=> TSPS-388 Move description input from start endpoint to prepare endpoint

service/src/main/java/bio/terra/pipelines/db/entities/PipelineQuota.java, service/src/main/java/bio/terra/pipelines/service/QuotasService.java, service/src/main/java/bio/terra/pipelines/stairway/QuotaConsumedValidationStep.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20241212_add_min_quota_for_pipelines.yaml, service/src/test/java/bio/terra/pipelines/db/entities/PipelineQuotaTest.java, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/QuotaConsumedValidationStepTest.java
For cost purposes, we want to have a floor to how much quota a single submission will consume.  For array imputation the floor is 500
before submission
after submission
https://broadworkbench.atlassian.net/browse/TSPS-385
=> TSPS-385 add min quota consumed to array imputation flight

.github/workflows/run-e2e-tests.yaml
Since we added an e2e test for the CLI, we renamed the e2e test files to more clearly distinguish between those used for the service and those used for the CLI. This PR updates the name of the e2e test yaml file we call to run the service e2e test.
Needs to be merged with this PR: https://github.com/broadinstitute/dsp-reusable-workflows/pull/59
https://broadworkbench.atlassian.net/browse/TSPS-331
=> TSPS-331 Update name of e2e test yaml

notification-templates/job_failed.html, notification-templates/job_succeeded.html
Checking in the changes made in SendGrid to add an instruction to email the scientific-services-support@broadinstitute.org email address for help (instead of replying to the email, which would go to the generic support@terra.bio address).
Updated in dev SendGrid (screenshot to note updated time):
And in prod SendGrid:
https://broadworkbench.atlassian.net/browse/TSPS-396
=> TSPS-396 Add support email instruction to notification templates

.github/actions/create-bee/action.yml, .github/workflows/run-e2e-tests.yaml
Relate our e2e slack messages to the associated "expected" app chart for the environment we're testing against
We also removed the e2e test being run on push to main in favor of running the e2e test on post [deploy hook for the dev environment](https://beehive.dsp-devops-prod.broadinstitute.org/environments/dev/chart-releases/teaspoons/deploy-hooks)
https://broadworkbench.atlassian.net/browse/TSPS-424
=> TSPS-424 fix up e2e test to have a environment specific slack message

service/src/main/java/bio/terra/pipelines/app/controller/GlobalExceptionHandler.java, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java
This PR addresses two cases around Bucket TTLs that will delete user data (inputs and outputs) in a way we can notify the user about
For the start endpoint, we return a 400 Bad Request for start requests whose created date is over EXPIRATION_DAYS old with a expiration related message
For the result endpoint, requests that are made EXPIRTATION_DAYS after the updated date, the service will not generate signed urls.  It will then be up to the CLI/UI to correctly parse the response and alert the user that their data is no longer available to download presumably by checking whether or not anything exists in the `pipeline_run_report.outputs` key
https://broadworkbench.atlassian.net/browse/TSPS-400
=> TSPS-400 add logic around pipeline runs and bucket TTLs

.github/actions/create-bee/action.yml
This shoudl help with our create bee job accidentally grabbign someone elses create bee job  - https://github.com/broadinstitute/workflow-dispatch/releases/tag/v4
N/A
=> update workflow dispatch version to v4 for create bee action

.github/workflows/run-e2e-tests.yaml, notification-templates/README.md, notification-templates/job_succeeded.html, service/src/main/java/bio/terra/pipelines/notifications/NotificationService.java, service/src/main/java/bio/terra/pipelines/notifications/TeaspoonsJobSucceededNotification.java, service/src/test/java/bio/terra/pipelines/notifications/NotificationServiceTest.java, service/src/test/java/bio/terra/pipelines/notifications/TeaspoonsJobSucceededNotificationTest.java
We want our notification email to inform the user how much time they have before their data gets deleted.
Changes that are a part of this pr in other repos
workbench libs - https://github.com/broadinstitute/workbench-libs/pull/1720 and https://github.com/broadinstitute/workbench-libs/pull/1721
thurloe - https://github.com/broadinstitute/thurloe/pull/375
https://broadworkbench.atlassian.net/browse/TSPS-402
Prod sendgrid template has been updated
This is the email i was sent after testing on my bee.  This change actually wouldnt look any different than the original template so i have two pictures to prove it was actually working as intended with a screenshot of some intermediate work that got deleted after.
This is a screenshot when we were displaying the number of days in the table
This is …
=> TSPS-402 Update Successful Notification with user data TTL

common/openapi.yml
This supports the CLI PR for TSPS-380 by specifying that certain fields in our API responses are required (not optional), meaning the CLI doesn't have to deal with the event that they are not present.
Tested with the CLI locally to ensure that this resolves the mypy type checking issues there.
https://broadworkbench.atlassian.net/browse/TSPS-380
=> TSPS-380 Set required response fields to aid in CLI type checking

.github/workflows/tag-publish.yml, buildSrc/src/main/groovy/bio.terra.pipelines.java-common-conventions.gradle
With this change, we now get back a 401 rather than a 500 from TCL/Sam when Sam doesn't recognize the user calling a Teaspoons API endpoint.
This supports a PR in the terralab repo: https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/pull/42
```
{
"message": "User not found",
"statusCode": 401,
"causes": []
}
```
https://broadworkbench.atlassian.net/browse/TSPS-404
=> TSPS-404 Update to TCL 1.1.36 to get 401 response for Sam user not found

.dockstore.yml, pipelines/imputation/scientificValidation/LiftoverVcfs.wdl, pipelines/imputation/scientificValidation/README.md, pipelines/imputation/testing/CompareVcfs.wdl, pipelines/imputation/testing/LiftoverVcfs.wdl, pipelines/imputation/testing/README.md
Note none of this is used in the warp tests directly.
- Update CompareVcfs test wdl to match warp test
- Add LiftoverVcfs wdl here (moved over from warp branch)
In support of work in https://broadworkbench.atlassian.net/browse/TSPS-222
=> TSPS-222 Updates for warp setup

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/QuotasController.java, service/src/main/java/bio/terra/pipelines/common/utils/QuotaUnitsEnum.java, service/src/main/java/bio/terra/pipelines/db/entities/PipelineQuota.java, service/src/main/java/bio/terra/pipelines/db/entities/converters/QuotaUnitsConverter.java, service/src/main/java/bio/terra/pipelines/db/repositories/PipelineQuotasRepository.java, service/src/main/java/bio/terra/pipelines/service/QuotasService.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20250225_add_quota_units.yaml, service/src/test/java/bio/terra/pipelines/controller/QuotasControllerTest.java, service/src/test/java/bio/terra/pipelines/db/entities/PipelineQuotaTest.java, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java, service/src/test/java/bio/terra/pipelines/testutils/MockMvcUtils.java
Each pipeline should have its quota unit defined. This PR adds a `quota_units` field to the `pipeline_quotas` table in the teaspoons database; the string value of `QuotaUnitsEnum` is meant to be the plural version of the unit, e.g. "samples" rather than "sample". We include this field in the `QuotaWithDetails` API response that users receive when they query their quota status for a pipeline.
https://broadworkbench.atlassian.net/browse/TSPS-405
=> TSPS-405 Add quota units to pipeline quotas

service/src/main/java/bio/terra/pipelines/app/controller/GlobalExceptionHandler.java
We get Sentry alerts often for seemingly spam/bot calls to existing paths with invalid methods (POST, PROPFIND). Similar to https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/89, we don't send these to Sentry but do log that we did so.  
https://broadworkbench.atlassian.net/browse/TSPS-345
=> TSPS-345 Mute sentry alerts for HttpRequestMethodNotSupportedException

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelinesApiController.java, service/src/main/java/bio/terra/pipelines/common/utils/CommonPipelineRunStatusEnum.java, service/src/main/java/bio/terra/pipelines/service/PipelinesService.java, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20250305_update_array_imputation_version.yaml, service/src/test/java/bio/terra/pipelines/service/PipelinesServiceTest.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
add file_suffix value to pipeline details inputs section
removed regex that forced tool version to match pipeline version
update array_imputation version to 1
_Please replace this description with a concise description of this Pull Request._
https://broadworkbench.atlassian.net/browse/TSPS-447
updated e2e test to match these version changes - https://github.com/broadinstitute/dsp-reusable-workflows/pull/73
=> TSPS-447 add file suffix to pipeline details response, update array_impuation version, remove admin update pipeline regex

service/src/main/java/bio/terra/pipelines/service/QuotasService.java, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java
This use case does happen in practice if a users first submission is rolled back by stairway.  The rollback would try to set the users quota back to 0
https://broadworkbench.atlassian.net/browse/TSPS-448
=> TSPS-448 allow user quota consumed to be updated to 0

.github/workflows/tag-publish.yml
This change is needed in order to be able to increment the major version of our service when running it manually.  At least for now until we decide we want some other logic like commit message or w/e to increment the version for us.
N/A
=> update tag publish job to create new tag even when no changes exist from latest tag

service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20250324_update_array_imputation_default_quota_to_2500.yaml, service/src/test/java/bio/terra/pipelines/service/QuotasServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/steps/common/QuotaConsumedValidationStepTest.java
For our prod release we want to only give users 2500 default quota.  This is so we can allow more users to use our service for free.
https://broadworkbench.atlassian.net/browse/TSPS-439
=> TSPS-439 update array_imputation default quota to 2500

service/src/main/java/bio/terra/pipelines/service/PipelineInputsOutputsService.java, service/src/test/java/bio/terra/pipelines/service/PipelineInputsOutputsServiceTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java
Adds a progress bar to the curl upload command that's supplied to users after preparing their pipeline run.
Api response before:
```
{
"jobId": "3fa85f64-5717-4562-b3fc-2c963f66afa2",
"fileInputUploadUrls": {
"multiSampleVcf": {
"curlCommand": "curl -X PUT -H 'Content-Type: application/octet-stream' --upload-file /Users/mbemis/Desktop/test-upload.vcf.gz '<SIGNED URL REDACTED>'",
"signedUrl": "<SIGNED URL REDACTED>"
}
}
}
```
Api response after:
```
{
"jobId": "3fa85f64-5717-4562-b3fc-2c963f66afa1",
"fileInputUploadUrls": {
"multiSampleVcf": {
"curlCommand": "curl --progress-bar -X PUT -H 'Content-Type: application/octet-stream' --upload-file /Users/mbemis/Desktop/test-upload.vcf.gz '<SIGNED URL REDACTED>' | cat",
"signedUrl": "<SIGNED URL REDACTED>"
}
}
}
```
Command run before:
``` …
```
=> TSPS-351 Add progress bar to curl upload command

ui/allofus-anvil-imputation/acknowledgments.html, ui/allofus-anvil-imputation/css/style.css, ui/allofus-anvil-imputation/index.html
This add links in acknowledgments, improves accessibility, and refines some layout.  It also trims the URL from "acknowledgments.html" to  "acknowledgments" when linked from the main page.
https://broadworkbench.atlassian.net/browse/TSPS-468
=> TSPS-468 Refine acknowledgments

ui/allofus-anvil-imputation/acknowledgments/index.html, ui/allofus-anvil-imputation/css/style.css, ui/allofus-anvil-imputation/deploy.py, ui/allofus-anvil-imputation/index.html, ui/allofus-anvil-imputation/readme.md
This adds a Python script  to deploy changes to a GCS bucket for each environment, and related documentation for the marketing UI.  It also refines some web content.
The dev and prod deployments now use GCS buckets instead of GitHub Pages, given SSL certificate issues with the latter.  So I'll disable GitHub Pages upon merging this PR, unless anyone objects.
https://broadworkbench.atlassian.net/browse/TSPS-468
=> TSPS-468 Add deployment script

ui/allofus-anvil-imputation/css/style.css
This fixes a layout bug with non-default browser settings for font size.  
These settings can be changed in Chrome by opening the dot menu in top right, "Settings", "Appearance", then changing "Font size" from "Medium (Recommended)" to "Large" or "Very large".
Non-default, "Large" font size browser setting
Default, "Medium" font size browser setting
Non-default, "Large" font size browser setting
Default, "Medium" font size browser setting
_Please replace this description with a concise description of this Pull Request._
https://broadworkbench.atlassian.net/browse/TSPS-468
=> TSPS-468 Fix layout for non-default browser font size

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelineRunsApiController.java, service/src/main/java/bio/terra/pipelines/db/repositories/PipelineRunsRepository.java, service/src/main/java/bio/terra/pipelines/service/PipelineRunsService.java, service/src/test/java/bio/terra/pipelines/controller/PipelineRunsApiControllerTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineRunsServiceTest.java
Adds a couple of new fields to the getAllPipelineRuns response, which will help populate the Job History page in the Imputation UI.
Related Imputation UI PR: https://github.com/DataBiosphere/terra-ui/pull/5327
https://broadworkbench.atlassian.net/browse/TSPS-506
=> [TSPS-506] Add `totalResults` and `quotaConsumed` fields to getAllPipelineRuns response

notification-templates/job_failed.html, notification-templates/job_succeeded.html
We want to move away from advertising Terra in favor of advertising DSP/Broad, so here we're changing the "about" text at the bottom of notification emails as well as removing the top green Terra bar.
Before:
After:
After approval but before merging, need to update the prod templates in sendgrid.
https://broadworkbench.atlassian.net/browse/TSPS-533
=> TSPS-533 Update 'about us' section of notification emails to DSP

.github/workflows/build-and-test.yml, .github/workflows/workflow-tester.yml, README.md, scripts/postgres-init.sql, service/src/test/resources/application-test.yml
Here we update the tests and instructions for local development to use postgreSQL version 15, up from 13.1, to match the version running in our live environments (currently 15.12). Version 15 will be supported until 2028.
Note this does NOT involve any change to our live environments, as they are already on version 15.
I've tested this in my local environment and am able to run the service locally using postgres 15. 
https://broadworkbench.atlassian.net/browse/TSPS-308
=> TSPS-308 Update tests and local development instructions to postgreSQL 15

service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20250808_update_array_imputation_description.yaml
Updating the user-facing pipeline display name and description ahead of public launch. 
Previous pipeline info:
```
"pipelineName": "array_imputation",
"displayName": "All of Us/AnVIL Array Imputation",
"pipelineVersion": 1,
"description": "Phase and impute genotypes using Beagle 5.4 with the AoU/AnVIL reference panel of 515,579 samples.",
```
Updated pipeline info
```
"pipelineName": "array_imputation",
"displayName": "All of Us + AnVIL Array Imputation",
"pipelineVersion": 1,
"description": "Phase and impute genotypes using Beagle 5.5 with the All of Us + AnVIL reference panel of 515,579 samples.",
```
https://broadworkbench.atlassian.net/browse/TSPS-466
=> TSPS-466 Update description for array_imputation v1

.github/workflows/run-e2e-tests.yaml, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20250821_update_array_imputation_default_quota_to_2500.yaml
For our public release, we are setting the default quota for array_imputation to 2500 samples.
Note this also involves changing our e2e tests.
PR here: https://github.com/broadinstitute/dsp-reusable-workflows/pull/78
Successful test run here: https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/17135672520/job/48611518783
https://broadworkbench.atlassian.net/browse/TSPS-580
=> TSPS-580 Set array_imputation default quota to 2500 for public release

service/src/main/java/bio/terra/pipelines/common/utils/PipelineVariableTypesEnum.java, service/src/main/java/bio/terra/pipelines/service/PipelineInputsOutputsService.java, service/src/main/java/bio/terra/pipelines/stairway/steps/common/FetchOutputsFromDataTableStep.java, service/src/test/java/bio/terra/pipelines/common/utils/PipelineVariableTypesEnumTest.java, service/src/test/java/bio/terra/pipelines/service/PipelineInputsOutputsServiceTest.java, service/src/test/java/bio/terra/pipelines/stairway/steps/common/FetchOutputsFromDataTableStepTest.java, service/src/test/java/bio/terra/pipelines/testutils/TestUtils.java
[The previous PR](https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/242) refactored our process for extracting WDL outputs but failed to support the Integer output of the QuotaConsumed WDL.
Here we add processing of outputs to ensure the correct type, as well as support for boolean type inputs/outputs (which we will need shortly).
e2e test run: https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/17413480419/job/49436988580
https://broadworkbench.atlassian.net/browse/TSPS-568
=> TSPS-568 part 1 FIX: support integer and boolean outputs

common/openapi.yml, service/src/main/java/bio/terra/pipelines/app/controller/PipelinesApiController.java, service/src/test/java/bio/terra/pipelines/controller/PipelinesApiControllerTest.java
It would be useful for users to be able to see not only what inputs a pipeline takes, but also what they can expect to get as outputs. Here we're adding the output definitions to the getPipelineDetails response.
Before:
```
{
"pipelineName": "array_imputation",
"displayName": "All of Us + AnVIL Array Imputation",
"pipelineVersion": 1,
"description": "Phase and impute genotypes using Beagle 5.5 with the All of Us + AnVIL reference panel of 515,579 samples.",
"type": "imputation",
"inputs": [
{
"name": "multiSampleVcf",
"type": "FILE",
"isRequired": true,
"fileSuffix": ".vcf.gz"
},
{
"name": "outputBasename",
"type": "STRING",
"isRequired": true
}
],
"pipelineQuota": {
"pipelineName": "array_imputation",
"defaultQuota": 2500,
"minQuotaConsumed": 500,
"quotaUnits": "SAMPLES"
}
}
```
After: …
=> TSPS-596 Add outputs to pipelines details response

notification-templates/job_failed.html, notification-templates/job_succeeded.html
Now that the UI is publicly available, we want to advertise it and point users there. This PR corresponds to updates to the job completion email notifications, which now instruct the users to use either the UI or the CLI to view their jobs and download their data.
Succeeded notification before:
Succeeded notification after:
Failed notification before:
Failed notification after:
https://broadworkbench.atlassian.net/browse/TSPS-631
=> TSPS-631 Update email notifications to point to UI
